### ISSUE TITLE
no code?

### ISSUE THREAD

**Issue by cmeesters** [fadilla-wahyudi/finemav#2]
Hi,

The paper mentioning this repo (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04506-9 ) says here should be some python code to find. Yet, there is no code at all, no release, no installer - nothing?

Is this an honest mistake? Should the code be found elsewhere?

Best regards,
Christian Meesters

**Comment by fadilla-wahyudi** [comment]
Hi Christian,

The Python code is [Additional file 1](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04506-9#additional-information) of the paper. The GitHub repository contains the Python executable file.

**Comment by cmeesters** [comment]
Hi,

The linked line reads

> Source code for the FineMAV program.

Hence, my assumption, that the source code is available. Also, the paper contains the line:

> The Python script can be found in Additional file 1. 

Instead, there is a dynamic executable (which will break once one of the APIs changes and is essentially unversioned). 

Admitted, it's your decision to not share the code and expect fellow scientist to work with the software as is. BTW, the GUI on my platform gives a number of warnings and errors, because the necessary font files are not installed. 

Best regards,
Christian Meesters

**Comment by fadilla-wahyudi** [comment]
Hi Christian,

The source code for the _FineMAV_ program is the Python script, which is Additional File 1.

Thank you for letting us know about the font warnings for the GUI version.

**Comment by cmeesters** [comment]
Hi,

Oh, sorry, I totally forgot to write my feedback.

With other words, there is a repository for source code management. And a licence which would possibly cover that code. However, it is preferred to host the code under the journal's coverage, only. This means that actually users are not allowed to use or alter it nor a chance to do so using the repository.

Perhaps this is a thought to consider for your next paper?

Best regards
Christian

**Comment by fadilla-wahyudi** [comment]
Hi Christian,

I think you raise a good point about the license. I will add the source code to the repository.
